<?php echo $this->render('header.phtml'); ?>
<script type="text/javascript" src="/public/scripts/tiny_mce/tiny_mce_gzip.js"></script>
<script type="text/javascript">
tinyMCE_GZ.init({
	plugins: '',
	themes : 'advanced',
	languages : 'en',
	disk_cache : true,
	debug : false
});
</script>
<!-- Needs to be seperate script tags! -->
<script type="text/javascript">
tinyMCE.init({
	mode : "textareas",
	theme : "advanced",
	theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,undo,redo,link,unlink,separator,code",
	theme_advanced_buttons2 : "",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "center",
	button_tile_map : true,
	extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]"
});
</script>
<div id="left">
	<div style="float: right; text-align: center; width: 260px">
		<br />
		<?php if(isset($this->playlist_to_edit['id']) && $this->playlist_to_edit['id']) : ?>
			<input type="button" value="Edit Playlist" onclick="location.href='/playlists/tracks/playlist_id/<?php echo $this->playlist_to_edit['id']; ?>/';" />
		<?php else: ?>
			<form action="/playlists/create/" method="post">
				<input type="submit" name="submit" value="Add Playlist">
				<input type="hidden" name="date" value="<?php echo $this->playlist_to_edit['date']; ?>">
				<input type="hidden" name="event_id" value="<?php echo $this->playlist_to_edit['event_id']; ?>">
				<input type="hidden" name="start_time" value="<?php echo $this->playlist_to_edit['start_time']; ?>">
				<input type="hidden" name="end_time" value="<?php echo $this->playlist_to_edit['end_time']; ?>">
				<input type="hidden" name="show_id" value="<?php echo $this->playlist_to_edit['show_id']; ?>">
				<input type="hidden" name="show_name" value="<?php echo $this->playlist_to_edit['show_name']; ?>">
			</form>	
		<?php endif; ?>
	</div>
	<h1><?php echo $this->date_formatted; ?></h1>
	<h3>
	[<a href="/playlists/manage/">Change Show</a>] &nbsp;&nbsp; 
	[<a href="/playlists/manage/event_id/<?php echo $this->event_id; ?>/switch/1/">Change Date</a>]
	</h3>
	
	<?php if ($this->the_message) : ?>
	    <div class="message"><?php echo $this->the_message; ?></div>
	<?php endif; ?>
	<div id="playlist_manage_image"  style="float: right; width: 260px; text-align: center;">
		<form>
			<fieldset><legend>Image Preview</legend></fieldset>
			<?php echo $this->the_image; ?>
		</form>
	</div>
	<?php echo $this->comment_form; ?>
	<br />
	<h1>All Shows of the Season</h1>
	<br />	
	<div class="mini_playlist_list">
		<table width="99%">
			
		<?php
		 	$week_no = 0;
			foreach($this->the_playlists as $playlist):
				$week_no++;
				if ($week_no % 2 == 0){
					$tr_class = 'even';
				} else {
					$tr_class = 'odd';
				}
				if ($playlist['date'] == $this->playlist_to_edit['date']){
					$tr_class = 'current';
				}
		 ?>
			<tr class="<?php echo $tr_class; ?>">
				<td>
					<div style="text-align: center; padding: 5px"><h3>
						<a href="/playlists/manage/event_id/<?php echo $this->event_id; ?>/date/<?php echo $playlist['date']; ?>/">
						<?php echo date("F j, Y", strtotime($playlist['date'])); ?>
						</a>
					</h3></div>
				<td><?php echo $this->createMiniPlaylistDescription($playlist, $this->the_shows, $this->the_djs); ?></td>
				<td>
					<div style="text-align: center; padding: 5px">
						<input type="button" value="Update Show Details" onclick="location.href='/playlists/manage/event_id/<?php echo $this->event_id; ?>/date/<?php echo $playlist['date']; ?>/';" />
						<br /><br />
					<?php if(isset($playlist['id']) && $playlist['id']) : ?>
						<input type="button" value="Edit Playlist" onclick="location.href='/playlists/tracks/playlist_id/<?php echo $playlist['id']; ?>/';" />
					<?php else: ?>
						<form action="/playlists/create/" method="post">
							<input type="submit" name="submit" value="Add Playlist">
							<input type="hidden" name="date" value="<?php echo $playlist['date']; ?>">
							<input type="hidden" name="event_id" value="<?php echo $playlist['event_id']; ?>">
							<input type="hidden" name="start_time" value="<?php echo $playlist['start_time']; ?>">
							<input type="hidden" name="end_time" value="<?php echo $playlist['end_time']; ?>">
							<input type="hidden" name="show_id" value="<?php echo $playlist['show_id']; ?>">
							<input type="hidden" name="show_name" value="<?php echo $playlist['show_name']; ?>">				
						</form>
					<?php endif; ?>
					</div>
				</td>
			</tr>
		<?php endforeach; ?>
		</table>
	</div>
</div><!-- left -->

<script type="text/javascript">
function toggleEditor(id) {
	var elm = document.getElementById(id);

	if (tinyMCE.getInstanceById(id) == null)
		tinyMCE.execCommand('mceAddControl', false, id);
	else
		tinyMCE.execCommand('mceRemoveControl', false, id);
}
</script>
<?php //echo $this->render('menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>
