<?php echo $this->render('header.phtml'); ?>

<div id="left">
	<h1>Playlist Editor - Select Date</h1>

	<h3>[<a href="/playlists/manage/">Change Show</a>]</h3>

	<div class="mini_playlist_list">
		<table width="99%">
			
		<?php
		 	$week_no = 0;
			foreach($this->the_playlists as $playlist):
				$week_no++;
				if ($week_no % 2 == 0){
					$tr_class = 'even';
				} else {
					$tr_class = 'odd';
				}
				if ($playlist['date'] == $this->playlist_to_edit['date']){
					$tr_class = 'upcoming';
				}
		 ?>
			<tr class="<?php echo $tr_class; ?>">
				<td>
					<div style="text-align: center; padding: 5px"><h3>
						<a href="/playlists/manage/event_id/<?php echo $this->event_id; ?>/date/<?php echo $playlist['date']; ?>/">
						<?php echo date("F j, Y", strtotime($playlist['date'])); ?>
						</a>
					</h3></div>
				<td><?php echo $this->createMiniPlaylistDescription($playlist, $this->the_shows, $this->the_djs); ?></td>
				<td>
					<div style="text-align: center; padding: 5px">
						<input type="button" value="Update Show Details" onclick="location.href='/playlists/manage/event_id/<?php echo $this->event_id; ?>/date/<?php echo $playlist['date']; ?>/';" />
						<br /><br />
					<?php if(isset($playlist['id']) && $playlist['id']) : ?>
						<input type="button" value="Edit Playlist" onclick="location.href='/playlists/tracks/playlist_id/<?php echo $playlist['id']; ?>/';" />
					<?php else: ?>
						<form action="/playlists/create/" method="post">
							<input type="submit" name="submit" value="Add Playlist">
							<input type="hidden" name="date" value="<?php echo $playlist['date']; ?>">
							<input type="hidden" name="event_id" value="<?php echo $playlist['event_id']; ?>">
							<input type="hidden" name="start_time" value="<?php echo $playlist['start_time']; ?>">
							<input type="hidden" name="end_time" value="<?php echo $playlist['end_time']; ?>">
							<input type="hidden" name="show_id" value="<?php echo $playlist['show_id']; ?>">
							<input type="hidden" name="show_name" value="<?php echo $playlist['show_name']; ?>">				
						</form>
					<?php endif; ?>
					</div>
				</td>
			</tr>
		<?php endforeach; ?>
		</table>
	</div>
</div><!-- left -->

<?php echo $this->render('footer.phtml'); ?>
