<?php echo $this->render('header.phtml'); ?>
<div id="left">
				<h1>Welcome to <?php echo STATION_NAME ?> Library</h1>
				<h2><a href="/playlists/">Manage Playlists</a></h2>
                <p>Create and Edit playlists for past and future shows.</p>
				<p class="date"></p>
				<h2><a href="/shows/">View Show Pages / Past Playlists</a></h2>
                <p>View show information such as playlists and show descriptions for past and future shows.</p>
				<p class="date"></p>
				<h2><a href="/options/">Account Options</a></h2>
				<p>Edit your personal information or change your password.	</p>
				<p class="date"></p>
                
			</div><!-- left -->
<?php echo $this->render('index/menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>
