<?php echo $this->render('header.phtml'); ?>
<div id="left">
				<h1><?php echo $this->title;?></h1>
                
		        <div id="tabs">
		            <ul>
		                <li style="margin-left: 1px" id="tabHeader1"><a href="/schedule/addShow"><span>Add Show</span></a></li>
		                <li id="tabHeader2"><a href="/schedule/editShow"><span>Edit Show</span></a></li>
						<li id="tabHeader3"><a href="/schedule/browseShows"><span>Browse Shows</span></a></li>
		            </ul>
		        </div><!--End of tabs-->
		        <div id="tabscontent">
		            <div id="tabContent1" class="tabContent" style="display: none;"></div>
					<div id="tabContent2" class="tabContent" style="display: none;">
						<?php 
							if(isset($this->seasonselector) && $this->seasonselector){
								echo $this->render('schedule/seasonselector.phtml');
							} else {
								echo $this->render('schedule/form_editshow.phtml');
							}						
						?>
					</div>
					<div id="tabContent3" class="tabContent" style="display: none;"></div>

		        </div><!--End of tabscontent-->
</div><!-- left -->
<script type="text/javascript">
    /*show second tab*/
    toggleTab(2,3);
</script>
<?php echo $this->render('menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>