<div>	
<div class="excerpt">
	Begin typing the name of the show you wish to edit <b>(minimum 3 characters)</b>
</div>
<div id="searchShowForm">
	<form action="" onsubmit="return false;">
		<fieldset>
			<legend>Edit Show From <?php echo $this->season_title; ?></legend>
			<ol>
				<li><label for="autocomplete" class="element">Magic Search</label>
					<div class="element">
						<input type="text" id="autocomplete" name="autocomplete_parameter"/>
						<span id="indicator" style="display: none"><img src="/public/images/loading_small.gif" alt="Loading..." /></span>
					</div>
					<div id="autocomplete_choices" class="autocomplete"></div>
				</li>
			</ol>
		</fieldset>
	</form>
</div>
<br /><br />

<div id="hidden_form" style="display: none">
	<div id="loading_editShowForm" style="text-align: center; display: none;"><img src="/public/images/loading.gif" /></div>
	<div id="editShowForm"></div>
</div>
</div>
<script type="text/javascript" language="javascript">
	function submitEditShowForm(form_element){
		
	    new Ajax.Updater('editShowForm', '/ajax/showEditForm', {
							asynchronous:true,
							evalScripts:true,
							onLoading: function(){ $('editShowForm').update('<div class="loading"></div>'); },
							parameters:Form.serialize(form_element)
							});
		return false;
	}
	/*makes the input element an autocompleter*/
	new Ajax.Autocompleter("autocomplete", "autocomplete_choices", "/ajax/autoCompleteShowNames/season_id/<?php echo $this->season_id;?>", {
	                        paramName: "search_term",
	                        minChars: 3,
	                        indicator: 'indicator', 
	                        afterUpdateElement: updateEditShowForm
	                        });
	
	/*grabs the form on user selection */
	function updateEditShowForm(element, li){
		getEditShowForm(li.id);
	}
	
	function getEditShowForm(show_id){
		if ($('hidden_form').style.display == 'none'){
			new Effect.SlideDown('hidden_form', {duration: 0.3});
		}
	    new Ajax.Updater('editShowForm', '/ajax/showEditForm', {
							onComplete:function(){ new Effect.Highlight('editUserForm');},
							onLoading: function(){ $('editShowForm').update('<div class="loading"></div>'); },
	                        asynchronous:true,
	                        parameters: {show_id: show_id}
	                        });
	}
	/*used to autograb show to edit if referred from another page*/
	<?php if (isset($this->show_id)): ?>
		getEditShowForm(<?php echo $this->show_id; ?>);
	<?php endif; ?>
</script>