<?php $rowHeight = 59; ?>
<style type="text/css">
div#week_container{
	padding: 0px 0 0 0px; 
	margin: 0 auto 0px auto;
}
.weekButton{
	width:80px;
	font-size:0.8em;
	font-family:arial;
}
#weekScheduler_container{
	border:1px solid #000;
	width:986px;	
}

.weekScheduler_appointments_day{	/* Column for each day */
	width:130px;
	float:left;
	background-color: #EEE;
	border-right:1px solid #ccc;	
	position:relative;
}
#weekScheduler_top{
	background-color:buttonface;
	height:20px;
	border-bottom:1px solid #ACA899;
}
.calendarContentTime,.spacer{
	background-color:buttonface;
	text-align:center;
	font-family:arial;
	font-size:28px;
	line-height:<?php echo $rowHeight; ?>px;
	height:<?php echo $rowHeight; ?>px;	/* Height of hour rows */
	
	border-right:1px solid #ccc;
	width:50px;
}

.weekScheduler_appointmentHour{	/* Small squares for each hour inside the appointment div */
	height:<?php echo $rowHeight; ?>px; /* Height of hour rows */
	border-bottom:1px solid #ccc;	
}

.spacer{
	height:20px;
	float:left;
}	

#weekScheduler_hours{
	width:50px;
	float:left;
}
.calendarContentTime{
	border-bottom:1px solid #ACA899;

}

#weekScheduler_appointments{	/* Big div for appointments */
	width:917px;
	float:left;
}
.calendarContentTime .content_hour{
	font-size:10px;
	text-decoration:superscript;	
	vertical-align:top;
	line-height:<?php echo $rowHeight; ?>px;
}
	
#weekScheduler_top{
	position:relative;
	clear:both;
}
#weekScheduler_content{
	clear:both;
	height:540px;
	position:relative;
	overflow:auto;
}
.days div{
	width:130px;
	float:left;
	background-color:buttonface;
	text-align:center;
	font-family:arial;
	height:20px;
	font-size:0.9em;
	line-height:20px;
	border-right:1px solid #ACA899;	
}

.weekScheduler_anAppointment{	/* A new appointment */
	position:absolute;
	background-color:#FFF;
	border:1px solid #000;
	z-index:1000;
	overflow:hidden;


}

.weekScheduler_appointment_header{	/* Appointment header row */
	height:4px;
	background-color:#ACA899;
}
.weekScheduler_appointment_headerActive{ /* Appointment header row  - when active*/
	height:4px;
	background-color:#00F;
}

.weekScheduler_appointment_textarea{	/* Textarea where you edit appointments */
	font-size:0.7em;
	font-family:arial;
}

.weekScheduler_appointment_txt{
	font-size:0.9em;
	font-family:arial;
	padding:2px;
	padding-top:5px;
	overflow:hidden;

}

.weekScheduler_appointment_footer{
	position:absolute;
	bottom:-1px;
	border-top:1px solid #000;
	height:4px;
	width:100%;
	font-size:0.8em;
	background-color:#000;
}

.weekScheduler_appointment_time{
	position:absolute;
	border:0px;
	right:0px;
	top:0px;
	width:70px;
	height:16px;
	z-index:100000;
	font-size:1em;
	padding:1px;
	background-color:#ccc;
}
.eventIndicator{
	background-color:#00F;
	z-index:50;
	display:none;
	position:absolute;
}

</style>
<script type="text/javascript" src="/public/scripts/schedule_ajax.js"></script>
<script type="text/javascript">
// It's important that this JS section is above the line below wher dhtmlgoodies-week-planner.js is included
var itemRowHeight=<?php echo $rowHeight; ?>;
var initDateToShow = '2006-02-13';	// Initial date to show
var seasonID = <?php echo $this->season_id; ?>;
</script>
<script src="/public/scripts/schedule_week.js?random=20060214" type="text/javascript"></script>
<form>
<div id="weekScheduler_container">
	<div id="weekScheduler_top">
		<div class="spacer"><span></span></div>
		<div class="days" id="weekScheduler_dayRow">
			<div>Sunday <span></span></div>
			<div>Monday <span></span></div>
			<div>Tuesday <span></span></div>
			<div>Wednesday <span></span></div>
			<div>Thursday <span></span></div>
			<div>Friday <span></span></div>
			<div>Saturday <span></span></div>					
		</div>	
	</div>
	<div id="weekScheduler_content">
		<div id="weekScheduler_hours">
		<?php
		
		$startHourOfWeekPlanner = 0;	// Start hour of week planner
		$endHourOfWeekPlanner = 23;	// End hour of weekplanner.
		
		$date = mktime($startHourOfWeekPlanner,0,0,5,5,2006);
		for($no=$startHourOfWeekPlanner;$no<=$endHourOfWeekPlanner;$no++){
			
			$hour = $no;
			
			// Remove these two lines in case you want to show hours like 08:00 - 23:00
			$suffix = date("a",$date);
			$hour = date("g",$date);
			
			// $suffix = "00"; // Enable this line in case you want to show hours like 08:00 - 23:00 
			
			
			$time = $hour."<span class=\"content_hour\">$suffix</span>";	
			$date = $date + 3600;		
			?>
			<div class="calendarContentTime"><?php echo $time; ?></div>
			<?php			
		}
		?>
		</div>	
		
		<div id="weekScheduler_appointments">
			<?php
			for($no=0;$no<7;$no++){	// Looping through the days of a week
				?>
				<div class="weekScheduler_appointments_day">
				<?php
				for($no2=$startHourOfWeekPlanner;$no2<=$endHourOfWeekPlanner;$no2++){
					echo "<div id=\"weekScheduler_appointment_hour".$no."_".$no2."\" class=\"weekScheduler_appointmentHour\"></div>\n";					
				}				
				?>				
				</div>
				<?php
			}
			?>		
		</div>
	</div>
</div>


<h2>How it works</h2>
<p>New Show: Hold your mouse down and drag</p>
<p>Move Show: Hold your mouse down at the top of an event and drag</p>
<p>Resize Show: Hold your mouse down at the bottom of an event and drag</p> 
<p>Edit show: Double click on the show you wish to edit and change details in the pop-up box</p>
<p>Delete event: Click on event and press delete key on your keyboard</p>
</form>
