		</div><!-- week_container -->
		<div id="links">
			<p>&nbsp;<!--<a href="http://www.kdvs.org/" style="color: #ffffff;">Main Site (www.kdvs.org)</a>--></p>
		</div>
	</div><!-- content -->

	<div id="additional">
		<!--<p><b>Be a better DJ with the "Word of the Day": </b><br />clemency \KLEM-uhn-see\, noun:<br />1. Disposition to forgive and spare, as offenders; mercy.</p>-->

	</div>
		
	<div id="whiteline"></div>

	<div id="footer">
		<p style="float: left;"><a href="#">Archive</a><img src="<?php echo $this->baseUrl; ?>/public/images/separator.gif" alt="" /><a href="#">RSS Feed</a>
		<br /><a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> and <a href="http://validator.w3.org/check?uri=referer">XHTML</a><img src="<?php echo $this->baseUrl; ?>/public/images/separator.gif" alt="" /><a href="#">Accessibility</a></p>

		<p style="float: right; text-align: right;"><a href="#">Report a Bug</a><br />
		Copyright &copy; 2007-2012 <a href="http://www.kdvs.org/">KDVS</a>, others.<img src="<?php echo $this->baseUrl; ?>/public/images/separator.gif" alt="" />Design: Luka Cvrk, <a href="http://www.solucija.com/">Solucija</a><img src="<?php echo $this->baseUrl; ?>/public/images/separator.gif" alt="" />Programming: Scott Biggart, Bryan Stitt, and Christopher Thielen.</p>
	</div>
</body>	
</html>
