
					</div><!-- articles -->

					<div id="links">
						<!--<p style="text-align: center;"><a href="<?php echo STATION_MAIN_SITE; ?>" style="color: #ffffff;">Main Site (<?php echo STATION_MAIN_SITE; ?>)</a></p>-->&nbsp;
					</div>
				</div><!-- content -->
			
				<div id="additional">
			<!--	<p><b>Be a better DJ with the "Word of the Day": </b><br />clemency \KLEM-uhn-see\, noun:<br />1. Disposition to forgive and spare, as offenders; mercy.</p>	-->
				</div>
					
				<div id="whiteline"></div>
			
				<div id="footer">
					<!--<p style="float: left;"><a href="http://kdvs.org/issues/">Report a Bug / Request a Feature</a><br /></p>-->

					<p style="float: right; text-align: right;">
					Copyright &copy; 2007-2012 <a href="http://kdvs.org/">KDVS</a> and others.<img src="<?php echo $this->baseUrl; ?>/public/images/separator.gif" alt="" />Design: Luka Cvrk, <a href="http://www.solucija.com/">Solucija</a><img src="<?php echo $this->baseUrl; ?>/public/images/separator.gif" alt="" />Programming: Scott Biggart, Bryan Stitt, and Christopher Thielen.</p>
				</div>
			</body>	
			</html>
