<div id="right">
	<div id="rightmenu">
        <?php echo $this->createSubMenu($this->c_controller);?>
	    <div id="searchform">
			<form method="post" class="search" action="">

				<p><input name="pojam" class="text" id="pojam" type="text" />
				<input name="search" class="button" value="Search" type="submit" /></p>
			</form>
		</div>
	</div>

	<div class="rightarticle">
		<p>If you find any bugs or would like features added or changed, please feel free to <a href="">contact the webmaster</a>.</p>

	</div>					

	<div class="rightarticle">
		<p><a href="">View Previous Playlists</a><br /><a href="">Read Recent Blog Comments</a><br /><a href="">View Your Show Page</a><br /><a href="">Download Your Shows</a><br />
		</p>
	</div>
</div><!-- right -->