<ul>
<?php
	$print_truncate = false;
	$count = 0;
 	foreach($this->albums as $album): 
		$count++;
		if($count > 10){
			$print_truncate = true;
			break;
		}
			
	?>
  <li id="<?php echo $album['id']; ?>"><b><?php echo $album['title']; ?></b><br /><span class="informal">&nbsp;by <?php echo $album['artist']; ?></span></li>  
<?php endforeach; ?>
</ul>
<?php if($print_truncate): ?>
<strong>More than 10 Results found...</strong>
<?php endif; ?>