<?php if ($this->the_message) : ?>
    <div class="message"><?php echo $this->the_message; ?></div>
<?php endif; ?>
	<div class="excerpt">
			<b>User Info</b><br />
			&nbsp;&nbsp + Username - cannot be changed<br />
			&nbsp;&nbsp + All information is required<br />
			&nbsp;&nbsp + Not available to public<br />
			<br />

	</div>
<?php //endif; ?>
<div id="userDetailsForm"><?php echo $this->the_form; ?></div>