<?php echo $this->render('header.phtml'); ?>
<div id="left">
				<h1>Account Options</h1>
				<h2><a href="/options/userDetails">Edit Profile Information</a></h2>
				<p>Edit personal details associated with your account and contact info.</p>
				<p class="date"></p>
				<h2><a href="/options/userDetails">Edit Profile Information</a></h2>
				<p>Change your password to something easier to remember or is more secure.</p>
				<p class="date"></p>
</div><!-- left -->
<?php echo $this->render('options/menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>
