<div id="right">
	<div id="rightmenu">
        <a href="/options/userDetails/">Edit Profile Information</a><a href="/options/changepass">Change Password</a>

	</div>

	<div class="rightarticle">
		<p>If you find any bugs or would like features added or changed, please feel free to <a href="http://kdvs.org/issues">submit an issue</a>.</p>

	</div>					
<!--
	<div class="rightarticle">
		<p><a href="">View Previous Playlists</a><br /><a href="">Read Recent Blog Comments</a><br /><a href="">View Your Show Page</a><br /><a href="">Download Your Shows</a><br />
		</p>
	</div>
-->
</div><!-- right -->