<?php echo $this->render('header.phtml'); ?>
<div id="left">
	<h2>Artist Search</h2>
			
    <div id="tabs">
        <ul>
            <li style="margin-left: 1px" id="tabHeader1"><a href="javascript:void(0)" onclick="toggleTab(1,2)"><span>Magic Search</span></a></li>
            <li id="tabHeader2"><a href="javascript:void(0)" onclick="toggleTab(2,2)" ><span>Advanced Search</span></a></li>
        </ul>
    </div><!--End of tabs-->
    <div id="tabscontent">
        <div id="tabContent1" class="tabContent" style="display: none;">
			<?php echo $this->render('search/artists_magic.phtml'); ?>
        </div>
        <div id="tabContent2" class="tabContent" style="display: none;">
			<?php echo $this->render('search/artists_advanced.phtml'); ?>
        </div>
    </div><!--End of tabscontent-->
</div><!-- left -->
<script type="text/javascript">
    /*show first tab*/
    toggleTab(1,2);
</script>
<?php echo $this->render('search/menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>