<?php echo $this->render('header.phtml'); ?>
<style>
#schedule {
   text-align: left;
   /*font-size: 0.9em*/
}
#schedule th {
	background: #BF3E18;
	color: #fff;
	margin: 3px;
	padding: 10px 1px;
	text-align: center;
	font-size: 14px;
}
#schedule td.odd, #playlist td.odd, #archive td.odd, #lisa_events td.odd, div.odd {
   /*background: #DDF1FF;*/
   background: #FFEBDD;
   padding: 3px;
}
#schedule td.even, #playlist td.even, #archive td.even, #lisa_events td.even, div.even {
   background: #abddff;
   padding: 3px;
}
/* schedule grid */
#schedule td.public {
    background: #D4E6FC;
	border:2px solid #fff;
}
#schedule td.music {
    background: #eee;
	border:2px solid #fff;
}
#schedule div.event_time {
    background: #3C6491;
    border: 0px;
    text-align: center;
    color: #fff;
	font-size: 1.1em;
}

</style>


	<h1>Fall 2008</h1>
	<h2>Temp Upcoming Schedule - Subject to Change</h2>

	<?php 
	    $output = "";
    	$output .= "<div id=\"schedule\">\n";
    	$output .= "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n";
    	$output .= "	<tr>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Sunday</th>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Monday</th>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Tuesday</th>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Wednesday</th>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Thursday</th>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Friday</th>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Saturday</th>\n";
     	$output .= "	</tr>\n";
     	
     	//now start output for individual events
     	$current_time = strtotime('00:00:00');
     	
     	$output .= "	<tr>\n";
        foreach($this->the_events as $event){
        	$event_id = $event['id'];
			if($event['end_time'] == '24:00:00'){
				$end_time = strtotime('00:00:00');
			} else {
        		$end_time = strtotime($event['end_time']);
    		}
			$start_time = strtotime($event['start_time']);
        	$time_diff = ($end_time - $start_time);
        	if($time_diff < 0){
        		$time_diff = $time_diff + 24*3600; //to deal with 00:00:00 being midnight
        	}
        	$rowspan = ceil($time_diff / (1800)); //number of half hours in show
        	
        	//delete
        	//$rowspan = $rowspan / 4;
        	
        	if ($start_time > $current_time){
        		$temp_diff = $start_time - $current_time;
        		$num_trs = ($temp_diff / 1800);
        		$current_time = $start_time;
        		
        		//echo "\n\n\n$num_trs";
        		for($i = 0; $i < $num_trs; $i++){
        			$output .= "	</tr>\n<tr>";
        		}
        	}
    		$output .= "<td class=\"music\" valign=\"top\" rowspan=\"$rowspan\">";
    		$output .= "<div class=\"schedule_event\">";
    		$output .= "<div class=\"event_time\">" . date("g:ia",$start_time) . "</div>";
    		$output .= $this->CreateEventDescription($event); //helper
    		$output .= "</div>";
    		$output .= "</td>";

        }
        
        //close last tr and put day info on bottom of table
        //$output .= "	</tr>\n<tr>\n</tr>\n<tr>\n</tr>\n<tr>\n</tr>\n<tr>\n";
		$output .= "	</tr>\n<tr>\n</tr>\n";
		$output .= "	<tr>\n";
     	$output .= "	<td class=\"music\" align=\"center\" valign=\"top\" width=\"14%\"><div class=\"event_time\">12:00am</div></td>\n";
     	$output .= "	<td class=\"music\" align=\"center\" valign=\"top\" width=\"14%\"><div class=\"event_time\">12:00am</div></td>\n";
     	$output .= "	<td class=\"music\" align=\"center\" valign=\"top\" width=\"14%\"><div class=\"event_time\">12:00am</div></td>\n";
     	$output .= "	<td class=\"music\" align=\"center\" valign=\"top\" width=\"14%\"><div class=\"event_time\">12:00am</div></td>\n";
     	$output .= "	<td class=\"music\" align=\"center\" valign=\"top\" width=\"14%\"><div class=\"event_time\">12:00am</div></td>\n";
     	$output .= "	<td class=\"music\" align=\"center\" valign=\"top\" width=\"14%\"><div class=\"event_time\">12:00am</div></td>\n";
     	$output .= "	<td class=\"music\" align=\"center\" valign=\"top\" width=\"14%\"><div class=\"event_time\">12:00am</div></td>\n";
     	$output .= "	</tr>\n";
		$output .= "<tr>\n";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Sunday</th>";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Monday</th>";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Tuesday</th>";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Wednesday</th>";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Thursday</th>";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Friday</th>";
     	$output .= "	<th align=\"center\" valign=\"top\" width=\"14%\">Saturday</th>";
     	$output .= "	</tr>\n";
     	$output .= "</table>\n";
	
	
		echo $output;
	 ?>
				

<?php echo $this->render('footer.phtml'); ?>
