<?php echo $this->render('header.phtml'); ?>
<div id="left">
				<h1><?php echo $this->title;?></h1>
                <p>Use this section to manage the albums in the <?php echo STATION_NAME ?> music library</p>
		        <div id="tabs">
		            <ul>
		                <li style="margin-left: 1px" id="tabHeader1"><a href="javascript:void(0)" onclick="toggleTab(1,3)"><span>Add Album</span></a></li>
		                <li id="tabHeader2"><a href="javascript:void(0)" onclick="toggleTab(2,3)" ><span>Edit Album</span></a></li>
		                <li id="tabHeader3"><a href="javascript:void(0)" onclick="toggleTab(3,3)"><span>Eat a Peach</span></a></li>
		            </ul>
		        </div><!--End of tabs-->
		        <div id="tabscontent">
		            <div id="tabContent1" class="tabContent" style="display: none;">
						<?php echo $this->render('music/form_addalbum_manual.phtml'); ?>
		            </div>
		            <div id="tabContent2" class="tabContent" style="display: none;">
		                <?php echo $this->render('music/form_editalbum.phtml'); ?>
		            </div>
		            <div id="tabContent3" class="tabContent" style="display: none;">
						<div>Peachy Keen</div>
		            </div>

		        </div><!--End of tabscontent-->
</div><!-- left -->
<script type="text/javascript">
    /*show first tab*/
    toggleTab(1,3);
</script>
<?php echo $this->render('music/menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>
