<?php echo $this->render('header.phtml'); ?>
<div id="left">
				<h1><?php echo $this->title;?></h1>
               
		        <div id="tabs">
		            <ul>
		                <li style="margin-left: 1px" id="tabHeader1"><a href="/music/addLabel"><span>Add Label</span></a></li>
		                <li id="tabHeader2"><a href="/music/editLabel"><span>Edit Label</span></a></li>
						<li id="tabHeader3"><a href="/music/browseLabels"><span>Browse Labels</span></a></li>
		            </ul>
		        </div><!--End of tabs-->
		        <div id="tabscontent">
		            <div id="tabContent1" class="tabContent" style="display: none;"></div>
					<div id="tabContent2" class="tabContent" style="display: none;">
						<?php echo $this->render('music/form_editlabel.phtml'); ?>
						
					</div>
					<div id="tabContent3" class="tabContent" style="display: none;"></div>

		        </div><!--End of tabscontent-->
</div><!-- left -->
<script type="text/javascript">
    /*show first tab*/
    toggleTab(2,3);
</script>
<?php echo $this->render('music/menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>