<?php echo $this->render('header.phtml'); ?>
<div id="left">
		<h2>Manage Users</h2>
				
        <div id="tabs">
            <ul>
                <li style="margin-left: 1px" id="tabHeader1"><a href="javascript:void(0)" onclick="toggleTab(1,3)"><span>Add User</span></a></li>
                <li id="tabHeader2"><a href="javascript:void(0)" onclick="toggleTab(2,3)" ><span>Edit User</span></a></li>
				<li id="tabHeader3"><a href="javascript:void(0)" onclick="toggleTab(3,3)" ><span>Browse Users</span></a></li>
            </ul>
        </div><!--End of tabs-->
        <div id="tabscontent">
            <div id="tabContent1" class="tabContent" style="display: none;">
				<?php echo $this->render('admin/form_adduser.phtml'); ?>
            </div>
            <div id="tabContent2" class="tabContent" style="display: none;">
				<?php echo $this->render('admin/form_edituser.phtml'); ?>
            </div>
            <div id="tabContent3" class="tabContent" style="display: none;">
				<?php echo $this->render('admin/browseusers.phtml'); ?>
            </div>
        </div><!--End of tabscontent-->			
				
				
				
</div><!-- left -->
<script type="text/javascript">
    /*show first tab*/
    toggleTab(1,3);
</script>
<?php echo $this->render('admin/menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>
